name: Deploy Tech Pulse API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenSSH (если отсутствует)
        run: sudo apt-get install -y openssh-client

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VDS_SSH_KEY }}
          SERVER_HOST: ${{ secrets.VDS_HOST }}
          SERVER_USER: ${{ secrets.VDS_USER }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
            cd /var/www/techpulse-api
            git pull origin main
            npm install
            npm run build
            pm2 restart techpulse-api || pm2 start npm --name 'techpulse-api' -- start
          "
